env:
  commonjs: true
  es6: true
  node: true
  jest: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  max-len:
    - error
    - code: 80
overrides:
  - files: ['*.test.js']
    rules:
      max-len: 'off'
